### ISSUE TITLE
FormatException: Invalid character found

### ISSUE THREAD

**Issue by avin1512** [dgkanatsios/AzureServicesForUnity#10]
I am getting below error while configuring Cosmos db table storage API with unity:
### FormatException: Invalid character found.
System.Convert.FromBase64String (System.String s) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Convert.cs:146)
AzureServicesForUnity.Shared.StorageUtilities.BuildStorageWebRequest (System.String url, System.String method, System.String accountName, System.String json) (at Assets/AzureServicesForUnity-master/Assets/AzureServicesForUnity/Storage/StorageUtilities.cs:70)
AzureServicesForUnity.Shared.TableStorageClient+<CreateTableIfNotExistsInternal>c__Iterator4.MoveNext () (at Assets/AzureServicesForUnity-master/Assets/AzureServicesForUnity/Storage/TableStorageClient.cs:200)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
AzureServicesForUnity.Shared.TableStorageClient:CreateTableIfNotExists(String, Action`1) (at Assets/AzureServicesForUnity-master/Assets/AzureServicesForUnity/Storage/TableStorageClient.cs:51)
StorageUIScript:CreateTable() (at Assets/AzureServicesForUnity-master/Assets/AzureServicesForUnity/_Demo Scenes/StorageUIScript.cs:68)
UnityEngine.EventSystems.EventSystem:Update()

Can u help me please. Thankyou in Advance.

**Comment by dgkanatsios** [comment]
First of all, thanks for using the library. Just did a quick test and everything seems to work fine. What I did
- Cloned the project locally
- Created a Cosmos DB account on Azure Portal using Table Storage model
- Got the Cosmos DB connection string from the portal, it's like
```csharp
 var connectionString = "DefaultEndpointsProtocol=https;AccountName=gkanatsioscosmostest;AccountKey=aR44U1234hgUpbRO4UCRYYYYYYYf0OEU3UXXXXXXX6YxkY8aV7eSVzNw4j4gj4Nwdg==;TableEndpoint=https://gkanatsioscosmostest.table.cosmosdb.azure.com:443/;";
```
- Got the AccountName and the AccountKey and replaced them on *StorageUIScript.cs*, so the *Start* method code is like this

```csharp
 Globals.DebugFlag = true;

  if (Globals.DebugFlag)
      Debug.Log("instantiated Azure Services for Unity, version " + Globals.LibraryVersion);

  //select the backend storage type regarding on where your tables are located, either Azure Table Storage or CosmosDB
  //available choices are EndpointStorageType.TableStorage and EndpointStorageType.CosmosDBTableAPI
        TableStorageClient.Instance.EndpointStorageType = EndpointStorageType.CosmosDBTableAPI;

  //your storage account name
  TableStorageClient.Instance.SetAccountName("gkanatsioscosmostest");

  //for Table Storage, fill either one of the below authentication methods
  //for CosmosDB Table API, you should use the AuthenticationToken credential by setting it with your AccountKey

  TableStorageClient.Instance.AuthenticationToken = "aR44U1234hgUpbRO4UCRYYYYYYYf0OEU3UXXXXXXX6YxkY8aV7eSVzNw4j4gj4Nwdg==";
   
```

and everything worked like a charm. I did my tests using Unity 5.6, I suppose this would work as is in newer versions. Can you please try and let me know if you still have the issue?

Moreover, I'd encourage you to take a look [here](https://docs.microsoft.com/en-us/sandbox/gamedev/unity/azure-storage-unity) where we have documented how to work with the official Azure Storage libraries and Unity. Thanks!

**Comment by dgkanatsios** [comment]
Since there has been no response, I assume that everything is good. Closing
