### ISSUE TITLE
It throws Enable Exception on WebGL after putting Data to firebase.

### ISSUE THREAD

**Issue by ceojazzy** [dgkanatsios/AzureServicesForUnity#11]
hi,
first of all thankYOU for doing such nice work. I download it linked my firebase and etc. Now when i build and upload it to my server after 5 seconds it shows me this error after putting data in the firebase.
![screenshot_2](https://user-images.githubusercontent.com/31903098/52697550-7ddf6080-2f93-11e9-86d1-b829e630eb65.png)

**Comment by ceojazzy** [comment]
![image](https://user-images.githubusercontent.com/31903098/52697592-8fc10380-2f93-11e9-9b32-7540969296eb.png)
this is my build settings i have tried changing it to Full, None etc.

**Comment by dgkanatsios** [comment]
Hi, thanks for your comment :) This library is to be used with Azure services, not Firebase.

**Comment by ceojazzy** [comment]
ok can i use Azure database with this library? for unity Webgl

**Comment by dgkanatsios** [comment]
You can use Azure Table Storage which is like a NoSQL Database. Thanks!
